// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewsSite;

namespace ReviewsSite.Migrations
{
    [DbContext(typeof(DiscographyContext))]
    [Migration("20201014183319_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReviewsSite.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Early Career",
                            Description = "1963",
                            Image = "PleasePleaseMe.jpg",
                            Name = "Please Please Me"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Early Career",
                            Description = "1964",
                            Image = "MeettheBeatles.jpg",
                            Name = "Meet the Beatles"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Early Career",
                            Description = "1964",
                            Image = "HardDaysNight.jpg",
                            Name = "Hard Day's Night"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Early Career",
                            Description = "1964",
                            Image = "BeatlesforSale.jpg",
                            Name = "Beatles for Sale"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Mid-Career",
                            Description = "1965",
                            Image = "Help!.jpg",
                            Name = "Help!"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Mid-Career",
                            Description = "1965",
                            Image = "RubberSoul.jpg",
                            Name = "Rubber Soul"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Mid-Career",
                            Description = "1966",
                            Image = "Revolver.jpg",
                            Name = "Revolver"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Late Career",
                            Description = "1967",
                            Image = "SgtPepper.jpg",
                            Name = "Sgt. Pepper's Lonely Hearts Club Band"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Late Career",
                            Description = "1967",
                            Image = "MagicalMysteryTour.jpg",
                            Name = "Magical Mystery Tour"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Late Career",
                            Description = "1968",
                            Image = "WhiteAlbum.jpg",
                            Name = "White Album"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Late Career",
                            Description = "1969",
                            Image = "YellowSubmarine.jpg",
                            Name = "Yellow Submarine"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Late Career",
                            Description = "1969",
                            Image = "AbbeyRoad.jpg",
                            Name = "Abbey Road"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Late Career",
                            Description = "1970",
                            Image = "LetItBe.jpg",
                            Name = "Let It Be"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
